Documents/clase10/grupal08-01-main/config/routes.rb
Rails.application.routes.draw do
  resources :noticia
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "noticia#index"


end

Documents/clase10/grupal08-01-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Documents/clase10/grupal08-01-main/app/models/noticium.rb
class Noticium < ApplicationRecord
end

Documents/clase10/grupal08-01-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Documents/clase10/grupal08-01-main/app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  before_action :set_noticium, only: %i[ show edit update destroy ]

  # GET /noticia or /noticia.json
  def index
    @noticia = Noticium.all
    @a = 1
  end

  # GET /noticia/1 or /noticia/1.json
  def show
  end

  # GET /noticia/new
  def new
    @noticium = Noticium.new
  end

  # GET /noticia/1/edit
  def edit
  end

  # POST /noticia or /noticia.json
  def create
    @noticium = Noticium.new(noticium_params)

    respond_to do |format|
      if @noticium.save
        format.html { redirect_to noticium_url(@noticium), notice: "Noticium was successfully created." }
        format.json { render :show, status: :created, location: @noticium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia/1 or /noticia/1.json
  def update
    respond_to do |format|
      if @noticium.update(noticium_params)
        format.html { redirect_to noticium_url(@noticium), notice: "Noticium was successfully updated." }
        format.json { render :show, status: :ok, location: @noticium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia/1 or /noticia/1.json
  def destroy
    @noticium.destroy

    respond_to do |format|
      format.html { redirect_to noticia_url, notice: "Noticium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticium
      @noticium = Noticium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def noticium_params
      params.require(:noticium).permit(:encabezado, :cuerpo, :link, :tipo)
    end
end

Documents/clase10/grupal08-01-main/app/helpers/application_helper.rb
module ApplicationHelper
end

Documents/clase10/grupal08-01-main/app/helpers/noticia_helper.rb
module NoticiaHelper
end

Documents/clase10/grupal08-01-main/app/views/layouts/_navbar.html.erb
<nav class="container navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

Documents/clase10/grupal08-01-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grupal0801</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

Documents/clase10/grupal08-01-main/app/views/noticia/_form.html.erb
<%= form_with(model: noticium) do |form| %>
  <% if noticium.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(noticium.errors.count, "error") %> prohibited this noticium from being saved:</h2>

      <ul>
        <% noticium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :encabezado, style: "display: block" %>
    <%= form.text_area :encabezado %>
  </div>

  <div>
    <%= form.label :cuerpo, style: "display: block" %>
    <%= form.text_area :cuerpo %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_area :link %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.number_field :tipo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Documents/clase10/grupal08-01-main/app/views/noticia/_noticium.html.erb
<div id="<%= dom_id noticium %>">
  <p>
    <strong>Id:</strong>
    <%= noticium.id %>
  </p>

  <p>
    <strong>Encabezado:</strong>
    <%= noticium.encabezado %>
  </p>

  <p>
    <strong>Cuerpo:</strong>
    <%= noticium.cuerpo %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= noticium.link %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= noticium.tipo %>
  </p>

</div>

Documents/clase10/grupal08-01-main/app/views/noticia/_noticium2.html.erb
Este es un subarchivo de la Vista

TEMPLATE PARCIAL

Documents/clase10/grupal08-01-main/app/views/noticia/edit.html.erb
<h1>Editing noticium</h1>

<%= render "form", noticium: @noticium %>

<br>

<div>
  <%= link_to "Show this noticium", @noticium %> |
  <%= link_to "Back to noticia", noticia_path %>
</div>

Documents/clase10/grupal08-01-main/app/views/noticia/index.html.erb
<div class="container">
    <p style="color: green"><%= notice %></p>

    <h1>Noticia felices.com </h1>
    <p>En esta página vas poder las noticias felices del momento,también podras agregar noticias felices</p>


  <div id="noticia">
    <% @noticia.each do |noticium| %>
      <%= render noticium %>
      <p>
        <%= link_to "Show this noticium", noticium %>
      </p>
    <% end %>
  </div>

  <%= link_to "New noticium", new_noticium_path %>
</div>
<div class="container"> 
    <button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">Funciona el popover</button>
</div>

Documents/clase10/grupal08-01-main/app/views/noticia/new.html.erb
<div class="container">
  <h1>Nueva Noticia</h1>

  <%= render "form", noticium: @noticium %>

  <br>

  <div>
  <%= link_to "Back to noticia", noticia_path %>
  </div>

</div>

Documents/clase10/grupal08-01-main/app/views/noticia/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @noticium %>

<div>

  <%= link_to "Edit this noticium", edit_noticium_path(@noticium) %> |
  <%= link_to "Back to noticia", noticia_path %>

  <%= button_to "Destroy this noticium", @noticium, method: :delete %>
</div>