Documents/clase6/datospersonales/config/routes.rb
Rails.application.routes.draw do
  root 'contact#index'
  resources :contact
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Documents/clase6/datospersonales/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Documents/clase6/datospersonales/app/models/contact.rb
class Contact < ApplicationRecord

	
end

Documents/clase6/datospersonales/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Documents/clase6/datospersonales/app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contacto = Contact.all
  end

  def create
    @contacto = Contact.new(contact_params)
    @contacto.save
    if @contacto
      redirect_to root_path
    end
  end

  def new
      @contacto = Contact.new     
  end

  def contact_params
    params.require(:contact).permit(:name,:email,:comment) 
  end
end

Documents/clase6/datospersonales/app/helpers/application_helper.rb
module ApplicationHelper
end

Documents/clase6/datospersonales/app/helpers/bootstrap_icon_helper.rb
module BootstrapIconHelper
  def icon(name)
    %Q{
      <i class="bi bi-#{name}"></i>
    }
  end
end

Documents/clase6/datospersonales/app/helpers/contact_helper.rb
module ContactHelper
end

Documents/clase6/datospersonales/app/views/contact/index.html.erb
<div class="container">
	<div class="alert alert-info" role="alert">
  		<h2>INFORMACIÓN PROFESIONAL</h2>
	</div>
	<div class="accordion " id="accordionPanelsStayOpenExample">
  <div class="accordion-item alert alert-success">
    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        <h3>Perfil</h3>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
      <div class="accordion-body row">
      <div class="col-4"><%= image_tag('carlos') %></div><div class="col-8"><blockquote class="blockquote"><strong> <p>Soy Persona Emprendedora e Independiente, con buen sentido del Humor ,mis pasiones son la  programación y me gusta trabajar en equipo, me considero autodidacta, todo ámbito tecnológico es como un juego estratégico que siempre aprendes algo nuevo.</p></strong></blockquote></div><br> 
    <figure>
        <blockquote class="blockquote">
          <p>La Verdadera Cultura es aprender a dialogar con cualquier tipo de persona conocer vivencias y compartir conocimiento </p>
        </blockquote>
      <figcaption class="blockquote-footer">
           <cite title="Source Title">Carlos Vasquez</cite>
      </figcaption>
    </figure>
      <u><b>Mis hobbies: Son correr por la mañana  y el fútbol</b></u>
      <b>Gustos Musicales: Rock Nacional,Latino, Heavy Metal, Metal en Español, Jazz, Música Clásica, Música género 70-80-90, Música de Anime, Grupos Rockeros Argentinos, Me agrada la música folclórica</b>
      </div>
    </div>
  </div>
  <div class="accordion-item alert alert-warning">
    <h2 class="accordion-header " id="panelsStayOpen-headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
       <h3>Email</h3>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div class="accordion-body ">
        <strong>ingeinfo2006@gmail.com</strong>  
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        <h3>Información Adicional</h3>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
      <div class="accordion-body">
        <strong>Soy profesional especializado del área de la ingeniería de software e informática, encargado del desarrollo de aplicaciones en lo que respecta a su diseño y obtención de los algoritmos, así como de analizar las posibles utilidades y modificaciones necesarias de los sistemas operativos para una mayor eficacia de un sistema informático.</strong>
    </div>
  </div>
</div>
</div>
<div class="container alert alert-primary" role="alert">
  	<%= link_to 'CONTACTÁME', new_contact_path, class:'btn btn-primary'%>
</div>

Documents/clase6/datospersonales/app/views/contact/new.html.erb
<div class="container">
   <div class="card mt-5">
        <div class="card-header">	
           <h3 class="text text-secondary">	Formulario de Contacto</h3>
        </div>	
        <div class="card-body">
			<%= form_for @contacto, url:{action: :create} do |data| %>
            <div class="container alert alert-primary">
	   		    <div class="form-group row">	
					<label class="col-3">Nombre: </label>
					<div class="col-5"> 
						<%= data.text_field :name, class:'form-control' %>	
					</div>	       
			    </div>	
    		    <div class="row"><br></div>
			    <div class="form-group row">	
					<label class="col-3">Correo: </label>
					<div class="col-5"> 
            			<%= data.text_field :email, class:'form-control'%>
        			</div> 
			    </div>
			     <div class="row"><br></div>
			    <div class="form-group row">	
					<label class="col-3">Comentarios: </label>
					<div class="col-5"> 
    					<%= data.text_area :comment, class:'form-control' %>
    				</div>
			    </div>
			     <div class="row"><br></div>
				<button type="submit" name="button" class='btn btn-primary btn-lg'>
				<span>Enviar</span>
				</button>
				<% end %>
		   </div>
	 	</div>
    </div>
</div>	

Documents/clase6/datospersonales/app/views/layouts/_navbar.html.erb
<header>
      <!--Container del Navbar-->
      <div class="container">
        <nav class="row navbar navbar-light" style="background-color: #e3f2fd;">       
          <div class="col-md-3"> 
             <!--Logo -->         
              <a href="http://127.0.0.1:3000/" class="col-3-lg col-3-md  col-md-auto btn btn-outline-primary btn-lg">         
                  <i class="bi bi-person-circle"></i>
                  <b>Carlos Vasquez</b>
                  <i class="bi bi-laptop"></i>
              </a> 
          </div>
          <div class="col-md-7">
              <!-- <a href="#agentescontaminantes" class="btn btn-outline-primary "><i class="bi bi-house"></i> Inicio</a>
              <a href="#comentarios" class="btn btn-outline-dark pr-6"><i class="bi bi-folder-plus"></i> Ingresar</a>             
              <a href="#contacto" class="btn btn-outline-primary pr-6"><i class="bi bi-people-fill"></i> ¿Quienes Somos?</a>
               <a href="#contacto" class="btn btn-outline-dark pr-6"><i class="bi bi-person-bounding-box"></i> Contacto</a>
               <a href="#contacto" class="btn btn-outline-danger pr-6">Necesita Ayuda<i class="bi bi-question-circle-fill"></i></a> -->
          </div>         
          <div class="col-md-2">            
             <!--Facebook-->
              <a href="#" class="text-reset btn btn-primary btn-sm"><i class="bi bi-facebook"></i> </a> 
                <!--Twitter-->
              <a href="#" class="text-reset btn btn-info btn-sm"><i class="bi bi-twitter"></i></a>            
                <!--Instagram-->
              <a href="#" class="text-reset btn btn-warning btn-sm"><i class="bi bi-instagram"></i></a>
                <!--Pinterest-->
              <a href="#" class="text-reset btn btn-danger btn-sm"><i class="bi bi-pinterest btn-sm"></i> </a>
          </div>     
        </nav>              
      </div>
    </header>

Documents/clase6/datospersonales/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Información Profesional</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">   
  </head>

  <body> 
    <%= render "layouts/navbar"%>    
    <%= yield %>
  </body>
</html>